"""
generate_docs.py
----------------
Generate comprehensive HTML audit report from all PBIX analyzers.

Creates a single interactive HTML document with:
  - Executive summary
  - File metadata and health score
  - Visual inventory
  - Data lineage and orphaned objects
  - Consistency violations
  - Data model documentation
  - Recommendations

Orchestrates: pbix_analyzer, data_lineage, consistency_checker, metadata_extractor

Compatible with: PBRS (offline)
"""

import json
from pathlib import Path
from datetime import datetime


def _generate_html_report(metadata: dict, lineage: dict = None,
                          violations: dict = None, output_path: str = None) -> str:
    """Generate comprehensive HTML audit report."""

    lineage = lineage or {}
    violations = violations or {"violations": []}

    # Calculate health score (0-100)
    health = 100
    health -= violations.get("summary", {}).get("errors", 0) * 10
    health -= violations.get("summary", {}).get("warnings", 0) * 3
    health = max(0, min(100, health))

    # Build HTML
    html_parts = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        "<meta charset='UTF-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        "<title>PBIX Audit Report</title>",
        "<style>",
        _get_css(),
        "</style>",
        "</head>",
        "<body>",
        "<div class='container'>",
    ]

    # Header
    pbix_name = Path(metadata.get("file", {}).get("filename", "unknown.pbix")).stem
    html_parts.append(f"""
    <header class='header'>
        <h1>Power BI Audit Report</h1>
        <p class='subtitle'>{pbix_name}</p>
        <p class='timestamp'>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </header>
    """)

    # Executive Summary
    html_parts.append(_generate_summary_section(metadata, health, violations, lineage))

    # File Metadata
    html_parts.append(_generate_file_section(metadata))

    # Visuals Inventory
    html_parts.append(_generate_visuals_section(metadata))

    # Data Lineage
    html_parts.append(_generate_lineage_section(lineage))

    # Violations
    html_parts.append(_generate_violations_section(violations))

    # Data Model
    html_parts.append(_generate_datamodel_section(metadata))

    # Footer
    html_parts.append("""
    <footer class='footer'>
        <p>Generated by vizbuilder PBIX Analyzer Suite</p>
    </footer>
    </div>
    </body>
    </html>
    """)

    html_content = "\n".join(html_parts)

    if output_path:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)

    return html_content


def _get_css() -> str:
    """Return embedded CSS for the report."""
    return """
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    body { background: #f5f5f5; color: #333; line-height: 1.6; }
    .container { max-width: 1200px; margin: 0 auto; padding: 20px; }

    header.header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white; padding: 40px; border-radius: 8px; margin-bottom: 30px; }
    h1 { font-size: 32px; margin-bottom: 10px; }
    .subtitle { font-size: 20px; opacity: 0.9; }
    .timestamp { font-size: 12px; opacity: 0.8; margin-top: 10px; }

    section { background: white; padding: 30px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    h2 { font-size: 24px; margin-bottom: 20px; color: #667eea; border-bottom: 2px solid #667eea; padding-bottom: 10px; }
    h3 { font-size: 18px; margin: 15px 0 10px; color: #555; }

    .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px; }
    .summary-card { background: #f9f9f9; padding: 15px; border-radius: 6px; border-left: 4px solid #667eea; }
    .summary-card.error { border-left-color: #e74c3c; }
    .summary-card.warning { border-left-color: #f39c12; }
    .summary-card.success { border-left-color: #27ae60; }
    .summary-label { font-size: 12px; color: #666; text-transform: uppercase; }
    .summary-value { font-size: 28px; font-weight: bold; color: #333; }

    .health-score { font-size: 48px; font-weight: bold; margin: 10px 0; }
    .health-score.good { color: #27ae60; }
    .health-score.warning { color: #f39c12; }
    .health-score.poor { color: #e74c3c; }

    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { background: #f0f0f0; padding: 12px; text-align: left; font-weight: 600; border-bottom: 2px solid #ddd; }
    td { padding: 10px 12px; border-bottom: 1px solid #eee; }
    tr:hover { background: #f9f9f9; }

    .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
    .badge.error { background: #e74c3c; color: white; }
    .badge.warning { background: #f39c12; color: white; }
    .badge.info { background: #3498db; color: white; }
    .badge.success { background: #27ae60; color: white; }

    .violation { background: #fff8f8; padding: 12px; margin: 10px 0; border-left: 3px solid #e74c3c; border-radius: 4px; }
    .violation.warning { background: #fffbf0; border-left-color: #f39c12; }
    .violation.info { background: #f0f7ff; border-left-color: #3498db; }

    .key-value { display: grid; grid-template-columns: 150px 1fr; gap: 15px; margin: 10px 0; }
    .key { font-weight: 600; color: #555; }
    .value { color: #333; }

    footer.footer { text-align: center; padding: 20px; color: #999; font-size: 12px; }
    """


def _generate_summary_section(metadata: dict, health: int, violations: dict, lineage: dict) -> str:
    """Generate executive summary section."""
    file_info = metadata.get("file", {})
    lineage_info = lineage.get("orphaned_objects", {})

    health_class = "good" if health >= 80 else "warning" if health >= 60 else "poor"

    return f"""
    <section id='summary'>
        <h2>Executive Summary</h2>
        <div class='summary-grid'>
            <div class='summary-card success'>
                <div class='summary-label'>Pages</div>
                <div class='summary-value'>{metadata.get("report", {}).get("total_pages", 0)}</div>
            </div>
            <div class='summary-card success'>
                <div class='summary-label'>Visuals</div>
                <div class='summary-value'>{metadata.get("report", {}).get("total_visuals", 0)}</div>
            </div>
            <div class='summary-card success'>
                <div class='summary-label'>Tables</div>
                <div class='summary-value'>{metadata.get("datamodel", {}).get("total_tables", 0)}</div>
            </div>
            <div class='summary-card success'>
                <div class='summary-label'>Measures</div>
                <div class='summary-value'>{metadata.get("datamodel", {}).get("total_measures", 0)}</div>
            </div>
        </div>

        <h3>Health Score</h3>
        <div class='health-score {health_class}'>{health}/100</div>
        <p>File size: {file_info.get('size_readable', 'unknown')}</p>

        <h3>Issues Found</h3>
        <div class='summary-grid'>
            <div class='summary-card error'>
                <div class='summary-label'>Errors</div>
                <div class='summary-value'>{violations.get("summary", {}).get("errors", 0)}</div>
            </div>
            <div class='summary-card warning'>
                <div class='summary-label'>Warnings</div>
                <div class='summary-value'>{violations.get("summary", {}).get("warnings", 0)}</div>
            </div>
            <div class='summary-card'>
                <div class='summary-label'>Info</div>
                <div class='summary-value'>{violations.get("summary", {}).get("info", 0)}</div>
            </div>
        </div>

        <h3>Data Quality</h3>
        <div class='summary-grid'>
            <div class='summary-card'>
                <div class='summary-label'>Orphaned Tables</div>
                <div class='summary-value'>{len(lineage_info.get("tables", []))}</div>
            </div>
            <div class='summary-card'>
                <div class='summary-label'>Unused Measures</div>
                <div class='summary-value'>{len(lineage_info.get("measures", []))}</div>
            </div>
        </div>
    </section>
    """


def _generate_file_section(metadata: dict) -> str:
    """Generate file metadata section."""
    file_info = metadata.get("file", {})
    security = metadata.get("security", {})

    return f"""
    <section id='file-info'>
        <h2>File Information</h2>
        <div class='key-value'>
            <div class='key'>Filename:</div>
            <div class='value'>{file_info.get('filename', 'unknown')}</div>
            <div class='key'>Size:</div>
            <div class='value'>{file_info.get('size_readable', 'unknown')}</div>
            <div class='key'>Created:</div>
            <div class='value'>{file_info.get('created', 'unknown')}</div>
            <div class='key'>Modified:</div>
            <div class='value'>{file_info.get('modified', 'unknown')}</div>
            <div class='key'>PBIX Version:</div>
            <div class='value'>{metadata.get('pbix_version', 'unknown')}</div>
            <div class='key'>SecurityBindings:</div>
            <div class='value'><span class='badge {("success" if security.get("has_security_bindings") else "warning")}'>{security.get("status", "unknown")}</span></div>
        </div>
    </section>
    """


def _generate_visuals_section(metadata: dict) -> str:
    """Generate visuals inventory section."""
    pages = metadata.get("report", {}).get("pages", [])

    html = "<section id='visuals'><h2>Visual Inventory</h2>"

    for page in pages:
        html += f"<h3>{page['name']}</h3>"
        html += "<table><thead><tr><th>ID</th><th>Type</th><th>Title</th><th>Position</th><th>Size</th></tr></thead><tbody>"

        for visual in page.get("visuals", []):
            pos = visual.get("position", {})
            title = visual.get("title", "(no title)")
            title_badge = "success" if visual.get("has_title") else "warning"

            html += f"""
            <tr>
                <td>{visual['id']}</td>
                <td><span class='badge info'>{visual['type']}</span></td>
                <td><span class='badge {title_badge}'>{title}</span></td>
                <td>({pos.get('x', 0)}, {pos.get('y', 0)})</td>
                <td>{pos.get('w', 0)}x{pos.get('h', 0)}</td>
            </tr>
            """

        html += "</tbody></table>"

    html += "</section>"
    return html


def _generate_lineage_section(lineage: dict) -> str:
    """Generate data lineage section."""
    lineages = lineage.get("lineages", [])
    orphaned = lineage.get("orphaned_objects", {})

    html = "<section id='lineage'><h2>Data Lineage</h2>"
    html += f"<p>Lineages traced: {len(lineages)}</p>"

    if lineages:
        html += "<h3>Used Fields</h3><p>Fields with visual bindings detected.</p>"

    if orphaned.get("tables"):
        html += "<h3>Orphaned Objects</h3>"
        for table in orphaned["tables"][:5]:  # Show first 5
            html += f"<div class='violation'><strong>{table['name']}</strong>: {table['reason']}</div>"

    html += "</section>"
    return html


def _generate_violations_section(violations: dict) -> str:
    """Generate violations section."""
    viol_list = violations.get("violations", [])

    html = "<section id='violations'><h2>Consistency Issues</h2>"

    if not viol_list:
        html += "<p>No issues found!</p>"
    else:
        for viol in viol_list[:20]:  # Show first 20
            severity = viol.get("severity", "info")
            html += f"""
            <div class='violation {severity}'>
                <strong>{viol['category'].replace('_', ' ').title()}:</strong> {viol['message']}
                {f"<br><em>Suggestion: {viol['suggestion']}</em>" if viol.get('suggestion') else ""}
            </div>
            """

    html += "</section>"
    return html


def _generate_datamodel_section(metadata: dict) -> str:
    """Generate data model documentation section."""
    tables = metadata.get("datamodel", {}).get("tables", [])

    html = "<section id='datamodel'><h2>Data Model</h2>"
    html += f"<p>Total tables: {len(tables)}</p>"

    for table in tables[:5]:  # Show first 5 tables
        html += f"<h3>{table['name']}</h3>"
        html += f"<p>Columns: {len(table.get('columns', []))}, Measures: {len(table.get('measures', []))}</p>"

        if table.get("measures"):
            html += "<div style='margin-left: 20px; background: #f9f9f9; padding: 10px; border-radius: 4px;'>"
            for measure in table.get("measures", [])[:3]:  # Show first 3 measures
                expr = measure.get("expression", "")[:100]
                html += f"<div><strong>{measure['name']}</strong></div>"
                if expr:
                    html += f"<code>{expr}...</code>"
            html += "</div>"

    html += "</section>"
    return html


# ── Main Function ────────────────────────────────────────────────────────────

def generate_report(metadata_path: str, lineage_path: str = None,
                   violations_path: str = None, output_path: str = None) -> str:
    """
    Generate unified HTML audit report.

    Parameters
    ----------
    metadata_path : str
        Path to metadata.json from pbix_analyzer
    lineage_path : str, optional
        Path to lineage.json from data_lineage
    violations_path : str, optional
        Path to violations.json from consistency_checker
    output_path : str, optional
        Path to save HTML report

    Returns
    -------
    str : HTML content
    """
    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    lineage = {}
    if lineage_path and Path(lineage_path).exists():
        with open(lineage_path, "r", encoding="utf-8") as f:
            lineage = json.load(f)

    violations = {}
    if violations_path and Path(violations_path).exists():
        with open(violations_path, "r", encoding="utf-8") as f:
            violations = json.load(f)

    print(f"\n  Generating HTML report...")

    html = _generate_html_report(metadata, lineage, violations, output_path)

    if output_path:
        print(f"  [OK] Report saved: {output_path}")

    return html


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print(__doc__)
        print("Usage: python generate_docs.py <metadata.json> [lineage.json] [violations.json] [output.html]")
        sys.exit(1)

    metadata_path = sys.argv[1]
    lineage_path = sys.argv[2] if len(sys.argv) > 2 else None
    violations_path = sys.argv[3] if len(sys.argv) > 3 else None
    output_path = sys.argv[4] if len(sys.argv) > 4 else None

    try:
        print("=" * 60)
        print("  Documentation Generator")
        print("=" * 60)

        html = generate_report(metadata_path, lineage_path, violations_path, output_path)

        print("\n" + "=" * 60)
        print("  Report complete!")
        print("=" * 60)

    except Exception as e:
        print(f"\n[ERROR] {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
